### PR TITLE
Fix "include" filed

### PR DESCRIPTION
**Pull request by ivankravets**

### CODE REVIEW

**Comment by ToniCorinne** [comment]
Thank you for pointing out this issue. We have updated the library code and fixed this issue.

**Comment by ivankravets** [comment]
Thanks that deleted [library.json](http://docs.platformio.org/en/latest/librarymanager/config.html) from https://github.com/sparkfun/RedBot/tree/master/Libraries/Arduino .

 Should we delete this library from our Registry? http://platformio.org/#!/lib/show/60/RedBot

**Comment by ToniCorinne** [comment]
Hi @ivankravets - It'd be great to keep the library in your Registry, but we've moved the primary library files to their own repository [here](https://github.com/sparkfun/SparkFun_Redbot_Arduino_Library). I can add the .json file back in there if you can point out the template to me that we need to use. 

We just recently found out about your platform, so I'll be working on updating our other libraries to send your way! It's a really great tool :)

**Comment by ivankravets** [comment]
>  I can add the .json file back in there if you can point out the template to me that we need to use.

Try this
```json
{
  "name": "RedBot",
  "keywords": "robot, motor, driver",
  "description": "The RedBot is a motor driver and Arduino combination with various headers and connections, eliminating the need to stack multiple shields",
  "repository":
  {
    "type": "git",
    "url": "https://github.com/sparkfun/SparkFun_RedBot_Arduino_Library.git"
  },
  "version": "2.1.0",
  "frameworks": "arduino",
  "platforms": "atmelavr"
}
```

Here is docs for [library.json](http://docs.platformio.org/en/latest/librarymanager/config.html).

P.S: Please ping me when you add config if will switch this library to it.

**Comment by ivankravets** [comment]
> We just recently found out about your platform, so I'll be working on updating our other libraries to send your way! It's a really great tool :)

Thanks a lot! Does SparkFun have any boards/platforms which are not listed in our ecosystem?

See curent list http://platformio.org/#!/boards?filter%5Bvendor%5D=SparkFun

**Comment by ToniCorinne** [comment]
Alrighty, I just pushed those changes, so the RedBot library can be updated. 

We do have a couple more libraries we can send your way - what's the best submission form once we get the .json files set up?

**Comment by ivankravets** [comment]
You can create library.json and register it without us http://docs.platformio.org/en/latest/librarymanager/creating.html

**Comment by ivankravets** [comment]
Offtop: @ToniCorinne,  Does SparkFun have any boards/platforms which are not listed in our ecosystem?

**Pull request closed without merging**
